<?php

/**
 * @file
 * Contains external_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function external_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the external_news module.
    case 'help.page.external_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('External News for My Portal Website') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function external_news_theme() {
  return [
    'external_news' => [
      'variables' => [
        'news' => [],
      ],
    ],
  ];
}
